### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by artur99** [csutter/chester-atom-syntax#1]
What font are you using in the screenshot? :D
Thank you!

**Comment by denysbutenko** [comment]
:+1:

**Comment by csutter** [comment]
Sorry @artur99 @denysbutenko, I only just saw this issue.

The font is _Fira Mono_, part of the _Fira Sans_ family by Mozilla. You can grab it here: https://github.com/mozilla/Fira!

Hope that helps :smiley:
