### ISSUE TITLE
Deprecation warnings in Atom 1.13.0

### ISSUE THREAD

**Issue by gee-forr** [csutter/chester-atom-syntax#11]
Hi there,

Just letting you know that Atom 1.13.0's deprecation cop has raised a huge amount of deprecation warnings.

I'm unable to show them here, as the generated URI is too long.

Let me know if I can help in any way.

**Comment by Shaglock** [comment]
chester-atom-syntax/index.less
Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

atom-text-editor, :host => atom-text-editor,atom-text-editor
atom-text-editor .wrap-guide, :host .wrap-guide => atom-text-editor .wrap-guide,atom-text-editor .wrap-guide
atom-text-editor .indent-guide, :host .indent-guide => atom-text-editor .indent-guide,atom-text-editor .indent-guide
atom-text-editor .invisible-character, :host .invisible-character => atom-text-editor .invisible-character,atom-text-editor .invisible-character
atom-text-editor .gutter, :host .gutter => atom-text-editor .gutter,atom-text-editor .gutter
atom-text-editor .gutter .line-number.cursor-line, :host .gutter .line-number.cursor-line => atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line
atom-text-editor .gutter .line-number.cursor-line-no-selection, :host .gutter .line-number.cursor-line-no-selection => atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection
atom-text-editor .gutter .line-number.folded, :host .gutter .line-number.folded, atom-text-editor .gutter .line-number:after, :host .gutter .line-number:after, atom-text-editor .fold-marker:after, :host .fold-marker:after => atom-text-editor .gutter .line-number.folded,atom-text-editor .gutter .line-number.folded, atom-text-editor .gutter .line-number:after,atom-text-editor .gutter .line-number:after, atom-text-editor .fold-marker:after,atom-text-editor .fold-marker:after
atom-text-editor .invisible, :host .invisible => atom-text-editor .invisible,atom-text-editor .invisible
atom-text-editor .cursor, :host .cursor => atom-text-editor .cursor,atom-text-editor .cursor
atom-text-editor .selection .region, :host .selection .region => atom-text-editor .selection .region,atom-text-editor .selection .region
atom-text-editor .search-results .marker .region, :host .search-results .marker .region => atom-text-editor .search-results .syntax--marker .region,atom-text-editor .search-results .syntax--marker .region
atom-text-editor .search-results .marker.current-result .region, :host .search-results .marker.current-result .region => atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region
.comment => .syntax--comment
.entity.name.type => .syntax--entity.syntax--name.syntax--type
.entity.other.inherited-class => .syntax--entity.syntax--other.syntax--inherited-class
.keyword => .syntax--keyword
.keyword.control => .syntax--keyword.syntax--control
.keyword.operator => .syntax--keyword.syntax--operator
.keyword.other.special-method => .syntax--keyword.syntax--other.syntax--special-method
.keyword.other.unit => .syntax--keyword.syntax--other.syntax--unit
.storage => .syntax--storage
.constant => .syntax--constant
.constant.character.escape => .syntax--constant.syntax--character.syntax--escape
.constant.numeric => .syntax--constant.syntax--numeric
.constant.other.color => .syntax--constant.syntax--other.syntax--color
.constant.other.symbol => .syntax--constant.syntax--other.syntax--symbol
.variable => .syntax--variable
.variable.interpolation => .syntax--variable.syntax--interpolation
.variable.parameter.function => .syntax--variable.syntax--parameter.syntax--function
.invalid.illegal => .syntax--invalid.syntax--illegal
.string => .syntax--string
.string.regexp => .syntax--string.syntax--regexp
.string.regexp .source.ruby.embedded => .syntax--string.syntax--regexp .syntax--source.syntax--ruby.syntax--embedded
.string.other.link => .syntax--string.syntax--other.syntax--link
.punctuation.definition.comment => .syntax--punctuation.syntax--definition.syntax--comment
.punctuation.definition.string, .punctuation.definition.variable, .punctuation.definition.parameters, .punctuation.definition.array => .syntax--punctuation.syntax--definition.syntax--string, .syntax--punctuation.syntax--definition.syntax--variable, .syntax--punctuation.syntax--definition.syntax--parameters, .syntax--punctuation.syntax--definition.syntax--array
.punctuation.definition.heading, .punctuation.definition.identity => .syntax--punctuation.syntax--definition.syntax--heading, .syntax--punctuation.syntax--definition.syntax--identity
.punctuation.definition.bold => .syntax--punctuation.syntax--definition.syntax--bold
.punctuation.definition.italic => .syntax--punctuation.syntax--definition.syntax--italic
.punctuation.section.embedded => .syntax--punctuation.syntax--section.syntax--embedded
.support.class => .syntax--support.syntax--class
.support.function => .syntax--support.syntax--function
.support.function.any-method => .syntax--support.syntax--function.syntax--any-method
.entity.name.function => .syntax--entity.syntax--name.syntax--function
.entity.name.class, .entity.name.type.class => .syntax--entity.syntax--name.syntax--class, .syntax--entity.syntax--name.syntax--type.syntax--class
.entity.name.section => .syntax--entity.syntax--name.syntax--section
.entity.name.tag => .syntax--entity.syntax--name.syntax--tag
.entity.other.attribute-name => .syntax--entity.syntax--other.syntax--attribute-name
.entity.other.attribute-name.id => .syntax--entity.syntax--other.syntax--attribute-name.syntax--id
.meta.class => .syntax--meta.syntax--class
.meta.link => .syntax--meta.syntax--link
.meta.require => .syntax--meta.syntax--require
.meta.selector => .syntax--meta.syntax--selector
.meta.separator => .syntax--meta.syntax--separator
.none => .syntax--none
.markup.bold => .syntax--markup.syntax--bold
.markup.changed => .syntax--markup.syntax--changed
.markup.deleted => .syntax--markup.syntax--deleted
.markup.italic => .syntax--markup.syntax--italic
.markup.heading .punctuation.definition.heading => .syntax--markup.syntax--heading .syntax--punctuation.syntax--definition.syntax--heading
.markup.inserted => .syntax--markup.syntax--inserted
.markup.list => .syntax--markup.syntax--list
.markup.quote => .syntax--markup.syntax--quote
.markup.raw.inline => .syntax--markup.syntax--raw.syntax--inline
.source.gfm .markup => .syntax--source.syntax--gfm .syntax--markup
.source.gfm .markup.heading => .syntax--source.syntax--gfm .syntax--markup.syntax--heading
atom-text-editor[mini] .scroll-view, :host([mini]) .scroll-view => atom-text-editor[mini] .scroll-view,atom-text-editor .scroll-view

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by SpectralKH** [comment]
@csutter 
Here they are:

Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

atom-text-editor, :host => atom-text-editor,atom-text-editor
atom-text-editor .wrap-guide, :host .wrap-guide => atom-text-editor .wrap-guide,atom-text-editor .wrap-guide
atom-text-editor .indent-guide, :host .indent-guide => atom-text-editor .indent-guide,atom-text-editor .indent-guide
atom-text-editor .invisible-character, :host .invisible-character => atom-text-editor .invisible-character,atom-text-editor .invisible-character
atom-text-editor .gutter, :host .gutter => atom-text-editor .gutter,atom-text-editor .gutter
atom-text-editor .gutter .line-number.cursor-line, :host .gutter .line-number.cursor-line => atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line
atom-text-editor .gutter .line-number.cursor-line-no-selection, :host .gutter .line-number.cursor-line-no-selection => atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection
atom-text-editor .gutter .line-number.folded, :host .gutter .line-number.folded, atom-text-editor .gutter .line-number:after, :host .gutter .line-number:after, atom-text-editor .fold-marker:after, :host .fold-marker:after => atom-text-editor .gutter .line-number.folded,atom-text-editor .gutter .line-number.folded, atom-text-editor .gutter .line-number:after,atom-text-editor .gutter .line-number:after, atom-text-editor .fold-marker:after,atom-text-editor .fold-marker:after
atom-text-editor .invisible, :host .invisible => atom-text-editor .invisible,atom-text-editor .invisible
atom-text-editor .cursor, :host .cursor => atom-text-editor .cursor,atom-text-editor .cursor
atom-text-editor .selection .region, :host .selection .region => atom-text-editor .selection .region,atom-text-editor .selection .region
atom-text-editor .search-results .marker .region, :host .search-results .marker .region => atom-text-editor .search-results .syntax--marker .region,atom-text-editor .search-results .syntax--marker .region
atom-text-editor .search-results .marker.current-result .region, :host .search-results .marker.current-result .region => atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region
.comment => .syntax--comment
.entity.name.type => .syntax--entity.syntax--name.syntax--type
.entity.other.inherited-class => .syntax--entity.syntax--other.syntax--inherited-class
.keyword => .syntax--keyword
.keyword.control => .syntax--keyword.syntax--control
.keyword.operator => .syntax--keyword.syntax--operator
.keyword.other.special-method => .syntax--keyword.syntax--other.syntax--special-method
.keyword.other.unit => .syntax--keyword.syntax--other.syntax--unit
.storage => .syntax--storage
.constant => .syntax--constant
.constant.character.escape => .syntax--constant.syntax--character.syntax--escape
.constant.numeric => .syntax--constant.syntax--numeric
.constant.other.color => .syntax--constant.syntax--other.syntax--color
.constant.other.symbol => .syntax--constant.syntax--other.syntax--symbol
.variable => .syntax--variable
.variable.interpolation => .syntax--variable.syntax--interpolation
.variable.parameter.function => .syntax--variable.syntax--parameter.syntax--function
.invalid.illegal => .syntax--invalid.syntax--illegal
.string => .syntax--string
.string.regexp => .syntax--string.syntax--regexp
.string.regexp .source.ruby.embedded => .syntax--string.syntax--regexp .syntax--source.syntax--ruby.syntax--embedded
.string.other.link => .syntax--string.syntax--other.syntax--link
.punctuation.definition.comment => .syntax--punctuation.syntax--definition.syntax--comment
.punctuation.definition.string, .punctuation.definition.variable, .punctuation.definition.parameters, .punctuation.definition.array => .syntax--punctuation.syntax--definition.syntax--string, .syntax--punctuation.syntax--definition.syntax--variable, .syntax--punctuation.syntax--definition.syntax--parameters, .syntax--punctuation.syntax--definition.syntax--array
.punctuation.definition.heading, .punctuation.definition.identity => .syntax--punctuation.syntax--definition.syntax--heading, .syntax--punctuation.syntax--definition.syntax--identity
.punctuation.definition.bold => .syntax--punctuation.syntax--definition.syntax--bold
.punctuation.definition.italic => .syntax--punctuation.syntax--definition.syntax--italic
.punctuation.section.embedded => .syntax--punctuation.syntax--section.syntax--embedded
.support.class => .syntax--support.syntax--class
.support.function => .syntax--support.syntax--function
.support.function.any-method => .syntax--support.syntax--function.syntax--any-method
.entity.name.function => .syntax--entity.syntax--name.syntax--function
.entity.name.class, .entity.name.type.class => .syntax--entity.syntax--name.syntax--class, .syntax--entity.syntax--name.syntax--type.syntax--class
.entity.name.section => .syntax--entity.syntax--name.syntax--section
.entity.name.tag => .syntax--entity.syntax--name.syntax--tag
.entity.other.attribute-name => .syntax--entity.syntax--other.syntax--attribute-name
.entity.other.attribute-name.id => .syntax--entity.syntax--other.syntax--attribute-name.syntax--id
.meta.class => .syntax--meta.syntax--class
.meta.link => .syntax--meta.syntax--link
.meta.require => .syntax--meta.syntax--require
.meta.selector => .syntax--meta.syntax--selector
.meta.separator => .syntax--meta.syntax--separator
.none => .syntax--none
.markup.bold => .syntax--markup.syntax--bold
.markup.changed => .syntax--markup.syntax--changed
.markup.deleted => .syntax--markup.syntax--deleted
.markup.italic => .syntax--markup.syntax--italic
.markup.heading .punctuation.definition.heading => .syntax--markup.syntax--heading .syntax--punctuation.syntax--definition.syntax--heading
.markup.inserted => .syntax--markup.syntax--inserted
.markup.list => .syntax--markup.syntax--list
.markup.quote => .syntax--markup.syntax--quote
.markup.raw.inline => .syntax--markup.syntax--raw.syntax--inline
.source.gfm .markup => .syntax--source.syntax--gfm .syntax--markup
.source.gfm .markup.heading => .syntax--source.syntax--gfm .syntax--markup.syntax--heading
atom-text-editor[mini] .scroll-view, :host([mini]) .scroll-view => atom-text-editor[mini] .scroll-view,atom-text-editor .scroll-view
Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by gluons** [comment]
**Here is deprecation log:**

`chester-atom-syntax\index.less`

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

- `atom-text-editor, :host` => `atom-text-editor,atom-text-editor`
- `atom-text-editor .wrap-guide, :host .wrap-guide` => `atom-text-editor .wrap-guide,atom-text-editor .wrap-guide`
- `atom-text-editor .indent-guide, :host .indent-guide` => `atom-text-editor .indent-guide,atom-text-editor .indent-guide`
- `atom-text-editor .invisible-character, :host .invisible-character` => `atom-text-editor .invisible-character,atom-text-editor .invisible-character`
- `atom-text-editor .gutter, :host .gutter` => `atom-text-editor .gutter,atom-text-editor .gutter`
- `atom-text-editor .gutter .line-number.cursor-line, :host .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line`
- `atom-text-editor .gutter .line-number.cursor-line-no-selection, :host .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection`
- `atom-text-editor .gutter .line-number.folded, :host .gutter .line-number.folded, atom-text-editor .gutter .line-number:after, :host .gutter .line-number:after, atom-text-editor .fold-marker:after, :host .fold-marker:after` => `atom-text-editor .gutter .line-number.folded,atom-text-editor .gutter .line-number.folded, atom-text-editor .gutter .line-number:after,atom-text-editor .gutter .line-number:after, atom-text-editor .fold-marker:after,atom-text-editor .fold-marker:after`
- `atom-text-editor .invisible, :host .invisible` => `atom-text-editor .invisible,atom-text-editor .invisible`
- `atom-text-editor .cursor, :host .cursor` => `atom-text-editor .cursor,atom-text-editor .cursor`
- `atom-text-editor .selection .region, :host .selection .region` => `atom-text-editor .selection .region,atom-text-editor .selection .region`
- `atom-text-editor .search-results .marker .region, :host .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region,atom-text-editor .search-results .syntax--marker .region`
- `atom-text-editor .search-results .marker.current-result .region, :host .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region`
- `.comment` => `.syntax--comment`
- `.entity.name.type` => `.syntax--entity.syntax--name.syntax--type`
- `.entity.other.inherited-class` => `.syntax--entity.syntax--other.syntax--inherited-class`
- `.keyword` => `.syntax--keyword`
- `.keyword.control` => `.syntax--keyword.syntax--control`
- `.keyword.operator` => `.syntax--keyword.syntax--operator`
- `.keyword.other.special-method` => `.syntax--keyword.syntax--other.syntax--special-method`
- `.keyword.other.unit` => `.syntax--keyword.syntax--other.syntax--unit`
- `.storage` => `.syntax--storage`
- `.constant` => `.syntax--constant`
- `.constant.character.escape` => `.syntax--constant.syntax--character.syntax--escape`
- `.constant.numeric` => `.syntax--constant.syntax--numeric`
- `.constant.other.color` => `.syntax--constant.syntax--other.syntax--color`
- `.constant.other.symbol` => `.syntax--constant.syntax--other.syntax--symbol`
- `.variable` => `.syntax--variable`
- `.variable.interpolation` => `.syntax--variable.syntax--interpolation`
- `.variable.parameter.function` => `.syntax--variable.syntax--parameter.syntax--function`
- `.invalid.illegal` => `.syntax--invalid.syntax--illegal`
- `.string` => `.syntax--string`
- `.string.regexp` => `.syntax--string.syntax--regexp`
- `.string.regexp .source.ruby.embedded` => `.syntax--string.syntax--regexp .syntax--source.syntax--ruby.syntax--embedded`
- `.string.other.link` => `.syntax--string.syntax--other.syntax--link`
- `.punctuation.definition.comment` => `.syntax--punctuation.syntax--definition.syntax--comment`
- `.punctuation.definition.string, .punctuation.definition.variable, .punctuation.definition.parameters, .punctuation.definition.array` => `.syntax--punctuation.syntax--definition.syntax--string, .syntax--punctuation.syntax--definition.syntax--variable, .syntax--punctuation.syntax--definition.syntax--parameters, .syntax--punctuation.syntax--definition.syntax--array`
- `.punctuation.definition.heading, .punctuation.definition.identity` => `.syntax--punctuation.syntax--definition.syntax--heading, .syntax--punctuation.syntax--definition.syntax--identity`
- `.punctuation.definition.bold` => `.syntax--punctuation.syntax--definition.syntax--bold`
- `.punctuation.definition.italic` => `.syntax--punctuation.syntax--definition.syntax--italic`
- `.punctuation.section.embedded` => `.syntax--punctuation.syntax--section.syntax--embedded`
- `.support.class` => `.syntax--support.syntax--class`
- `.support.function` => `.syntax--support.syntax--function`
- `.support.function.any-method` => `.syntax--support.syntax--function.syntax--any-method`
- `.entity.name.function` => `.syntax--entity.syntax--name.syntax--function`
- `.entity.name.class, .entity.name.type.class` => `.syntax--entity.syntax--name.syntax--class, .syntax--entity.syntax--name.syntax--type.syntax--class`
- `.entity.name.section` => `.syntax--entity.syntax--name.syntax--section`
- `.entity.name.tag` => `.syntax--entity.syntax--name.syntax--tag`
- `.entity.other.attribute-name` => `.syntax--entity.syntax--other.syntax--attribute-name`
- `.entity.other.attribute-name.id` => `.syntax--entity.syntax--other.syntax--attribute-name.syntax--id`
- `.meta.class` => `.syntax--meta.syntax--class`
- `.meta.link` => `.syntax--meta.syntax--link`
- `.meta.require` => `.syntax--meta.syntax--require`
- `.meta.selector` => `.syntax--meta.syntax--selector`
- `.meta.separator` => `.syntax--meta.syntax--separator`
- `.none` => `.syntax--none`
- `.markup.bold` => `.syntax--markup.syntax--bold`
- `.markup.changed` => `.syntax--markup.syntax--changed`
- `.markup.deleted` => `.syntax--markup.syntax--deleted`
- `.markup.italic` => `.syntax--markup.syntax--italic`
- `.markup.heading .punctuation.definition.heading` => `.syntax--markup.syntax--heading .syntax--punctuation.syntax--definition.syntax--heading`
- `.markup.inserted` => `.syntax--markup.syntax--inserted`
- `.markup.list` => `.syntax--markup.syntax--list`
- `.markup.quote` => `.syntax--markup.syntax--quote`
- `.markup.raw.inline` => `.syntax--markup.syntax--raw.syntax--inline`
- `.source.gfm .markup` => `.syntax--source.syntax--gfm .syntax--markup`
- `.source.gfm .markup.heading` => `.syntax--source.syntax--gfm .syntax--markup.syntax--heading`
- `atom-text-editor[mini] .scroll-view, :host([mini]) .scroll-view` => `atom-text-editor[mini] .scroll-view,atom-text-editor .scroll-view`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by probablykasper** [comment]
This guy has not been active in years, so I doubt anythung is gonna happen.So I made the [chester-syntax](https://github.com/SpectralKH/chester-syntax) theme, which fixes this.

**Comment by csutter** [comment]
Sorry for the long delay in responding to issues, I've not been receiving notifications on this repo.

**Unfortunately I'm no longer using Atom and won't be maintaining this theme anymore.** I'll add a note to the `README` and will link to the more active forks.

Regardless of that: Thanks for using (and improving) an old little pet project of mine! 😃

**Comment by probablykasper** [comment]
@csutter I suggest updating the Atom package as well, so your new changes show inside Atom.

Additionally, something really nice would be to let someone take over this repo (Adding collaborators or transferring ownership), just because this repo has that popularity already.

**Comment by csutter** [comment]
@SpectralKH I'm happy to add you as a collaborator (might be easier to avoid issues with the repo URL changing?) if you would like to take over?

**Comment by probablykasper** [comment]
@csutter Sure, but try adding @RuslanIsrafilov as well because I'm not extremely experienced with package development.

**Comment by csutter** [comment]
@SpectralKH @RuslanIsrafilov Done! Feel free to take the deprecation notice out and push new builds – I think atom.io works on Github permissions so it should work :)

**Comment by probablykasper** [comment]
@csutter Update has been published, everything should work nicely now :D
