### ISSUE TITLE
Deprecated selector in `chester-atom-syntax\index.less`

### ISSUE THREAD

**Issue by jaffreyjoy** [csutter/chester-atom-syntax#14]
In `chester-atom-syntax\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor,
:host` => `atom-text-editor,atom-text-editor`

* `atom-text-editor .wrap-guide,
:host .wrap-guide` => `atom-text-editor .wrap-guide,atom-text-editor .wrap-guide`

* `atom-text-editor .indent-guide,
:host .indent-guide` => `atom-text-editor .indent-guide,atom-text-editor .indent-guide`

* `atom-text-editor .invisible-character,
:host .invisible-character` => `atom-text-editor .invisible-character,atom-text-editor .invisible-character`

* `atom-text-editor .gutter,
:host .gutter` => `atom-text-editor .gutter,atom-text-editor .gutter`

* `atom-text-editor .gutter .line-number.cursor-line,
:host .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line`

* `atom-text-editor .gutter .line-number.cursor-line-no-selection,
:host .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `atom-text-editor .gutter .line-number.folded,
:host .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,
:host .gutter .line-number:after,
atom-text-editor .fold-marker:after,
:host .fold-marker:after` => `atom-text-editor .gutter .line-number.folded,atom-text-editor .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,atom-text-editor .gutter .line-number:after,
atom-text-editor .fold-marker:after,atom-text-editor .fold-marker:after`

* `atom-text-editor .invisible,
:host .invisible` => `atom-text-editor .invisible,atom-text-editor .invisible`

* `atom-text-editor .cursor,
:host .cursor` => `atom-text-editor .cursor,atom-text-editor .cursor`

* `atom-text-editor .selection .region,
:host .selection .region` => `atom-text-editor .selection .region,atom-text-editor .selection .region`

* `atom-text-editor .search-results .marker .region,
:host .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region,atom-text-editor .search-results .syntax--marker .region`

* `atom-text-editor .search-results .marker.current-result .region,
:host .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region`

* `.comment` => `.syntax--comment`

* `.entity.name.type` => `.syntax--entity.syntax--name.syntax--type`

* `.entity.other.inherited-class` => `.syntax--entity.syntax--other.syntax--inherited-class`

* `.keyword` => `.syntax--keyword`

* `.keyword.control` => `.syntax--keyword.syntax--control`

* `.keyword.operator` => `.syntax--keyword.syntax--operator`

* `.keyword.other.special-method` => `.syntax--keyword.syntax--other.syntax--special-method`

* `.keyword.other.unit` => `.syntax--keyword.syntax--other.syntax--unit`

* `.storage` => `.syntax--storage`

* `.constant` => `.syntax--constant`

* `.constant.character.escape` => `.syntax--constant.syntax--character.syntax--escape`

**Comment by guidezpl** [comment]
Awaiting @csutter pull request approval, use https://atom.io/themes/improved-chester-atom-syntax

**Comment by probablykasper** [comment]
Update: Package is maintained by me now, and I just published an update.

Everything should be working nicely now :)
