### ISSUE TITLE
How install this theme?

### ISSUE THREAD

**Issue by Maharal** [csutter/chester-atom-syntax#16]

**Comment by rlnx** [comment]
@Maharal, [here is](http://flight-manual.atom.io/using-atom/sections/atom-packages) guide describing how to install atom packages, just search for chester-atom-syntax.

**Comment by probablykasper** [comment]
@Maharal I'm guessing you clicked "install" after searching for the package, so to enable the package you need to go to the "Themes" page and select Chester Atom as the syntax theme.
![screen shot 2017-06-11 at 1 27 51 pm](https://user-images.githubusercontent.com/11315492/27010669-d7193b02-4ea9-11e7-9f19-1e37813f929f.png)
