### ISSUE TITLE
Python operator "in" and "not" not hilighted as operators

### ISSUE THREAD

**Issue by hex007** [csutter/chester-atom-syntax#19]
![screenshot from 2018-03-10 00-52-49](https://user-images.githubusercontent.com/1689246/37240213-63244c80-23fd-11e8-87f4-8475010de5a4.png)

**Comment by probablykasper** [comment]
Fixed the issue, but only specifically for Python because I'm unaware whether it'll fix issues or cause new issues in other languages.

Go grab version 0.3.2 :)
