### ISSUE TITLE
operator highlighting

### ISSUE THREAD

**Issue by ccorcos** [csutter/chester-atom-syntax#2]
My name is Chester, so I basically have to use this. Not to mention, I like the colors ;)

But I've noticed that there is no colors for operators which doesnt look very good for coffeescript.

<img width="333" alt="screen shot 2015-07-26 at 10 42 40 pm" src="https://cloud.githubusercontent.com/assets/1794527/8899318/c08b95bc-33e7-11e5-8fb5-d4abe3f23bcf.png">

Would you mind coloring operators for this highlighter? I'd really appreciate it. :+1:

**Comment by probablykasper** [comment]
I may update my forked [chester-syntax](https://github.com/SpectralKH/chester-syntax) to look like this;
![screen shot 2017-01-28 at 6 57 40 pm](https://cloud.githubusercontent.com/assets/11315492/22398585/c11735f2-e58b-11e6-800c-747e451af545.png)

Tried with other colors as well, but was not satisfied. Not 100% sure about this either.

**Comment by csutter** [comment]
Sorry for the long delay in responding to issues, I've not been receiving notifications on this repo.

**Unfortunately I'm no longer using Atom and won't be maintaining this theme anymore.** I'll add a note to the `README` and will link to the more active forks.

Regardless of that: Thanks for using (and improving) an old little pet project of mine! 😃
