### ISSUE TITLE
Doesn't highlight variables

### ISSUE THREAD

**Issue by ferologics** [csutter/chester-atom-syntax#3]
You can see the variables aren't colored red when being defined and in other parts as well...

the language is python. I've looked into the base.less and everything seemed to be working so not sure what 's the problem with this.

[dropbox link](https://www.dropbox.com/s/lpohslx6jt4tw1q/Screenshot%202015-10-20%2020.07.20.png?dl=0)
![screenshot 2015-10-20 20 07 20](https://cloud.githubusercontent.com/assets/5576161/10626674/3cdf15fa-7766-11e5-914e-bc7de62e3932.png)

**Comment by csutter** [comment]
Sorry for the long delay in responding to issues, I've not been receiving notifications on this repo.

**Unfortunately I'm no longer using Atom and won't be maintaining this theme anymore.** I'll add a note to the `README` and will link to the more active forks.

Regardless of that: Thanks for using (and improving) an old little pet project of mine! 😃

**Comment by probablykasper** [comment]
This is actually a limitation of Atom's built-in packages. Variables do not get any special CSS classes that lets syntax themes style them, thus this happens in JavaScript too. However for languages like PHP, it's possible since all variables are prefixed with $.
