### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by zhiiwg** [csutter/chester-atom-syntax#4]
I like this theme, thanks for your work :+1: 
any plan to support markdown syntax highlight?

![image](https://cloud.githubusercontent.com/assets/4954007/11810694/e33e6088-a36a-11e5-98ca-56029fe3f91f.png)
markdown image

![image](https://cloud.githubusercontent.com/assets/4954007/11810702/fba128c2-a36a-11e5-9ffe-cdf0372c970b.png)
markdown link

**Comment by probablykasper** [comment]
Added to my fork of it, [chester-syntax](https://github.com/SpectralKH/chester-syntax). Unfortunately, Atom's language-markdown package isn't perfect, so full markdown syntax support is impossible; But I've done what I can.

**Comment by csutter** [comment]
Sorry for the long delay in responding to issues, I've not been receiving notifications on this repo.

**Unfortunately I'm no longer using Atom and won't be maintaining this theme anymore.** I'll add a note to the `README` and will link to the more active forks.

Regardless of that: Thanks for using (and improving) an old little pet project of mine! 😃

**Comment by probablykasper** [comment]
Added markdown highlighting for headers, links, images and tables in 0.2.0.
