### ISSUE TITLE
Other Editor Support

### ISSUE THREAD

**Issue by ahmad2smile** [csutter/chester-atom-syntax#6]
As Atom got alot of issues most of all its slow. Would there be support for other Editors like Brackets, VS Code or just for Visual Studio

**Comment by Gunny123** [comment]
I don't think this syntax is kept update to date. I'd love to see the syntax ported to Sublime Text 3, but I don't have the time to do it myself...

**Comment by csutter** [comment]
Sorry for the long delay in responding to issues, I've not been receiving notifications on this repo.

I might do a VS Code port of this theme at some point, but have been happy using other themes in VS Code and vim lately. Feel free to do whatever you want with this theme though!

**Unfortunately I'm no longer using Atom and won't be maintaining this theme anymore.** I'll add a note to the `README` and will link to the more active forks.

Regardless of that: Thanks for using (and improving) an old little pet project of mine! 😃

**Comment by Gunny123** [comment]
I don't think you understand the popularity of your theme. This is the theme that began it all for me! The first theme I ever installed too! 😭😩

**Comment by ahmad2smile** [comment]
Same here. I love this theme too and been using it for a long time now.

**Comment by probablykasper** [comment]
Hmmmm........ We'll see, I guess

**Comment by Gunny123** [comment]
30,000+ installs can't go wrong! 

Edit: The OG Chester theme is back and not deprecated. Fuck ya.

**Comment by ahmad2smile** [comment]
Thanks, for the Update.... <3

**Comment by gluons** [comment]
For VSCode, we can use @ceckenrode 's [vscode-chester-atom](https://github.com/ceckenrode/vscode-chester-atom). 🙂

**Comment by probablykasper** [comment]
@gluons Awesome :)
