### ISSUE TITLE
Colour conflicts in Python

### ISSUE THREAD

**Issue by d3v-null** [csutter/chester-atom-syntax#8]
This is only a minor issue and I wasn't sure whether or not to report it, so feel free to ignore this.

I really love the aesthetics of this theme but one thing I couldn't handle was how close the colours for control characters and normal characters were in Python, which unfortunately made me swap to a different theme. Here's an example

<img width="469" alt="screen shot 2016-10-25 at 11 26 45 am" src="https://cloud.githubusercontent.com/assets/2578076/19668816/0f3831b8-9aa6-11e6-8cc3-d0510f941a81.png">

**Comment by csutter** [comment]
Sorry for the long delay in responding to issues, I've not been receiving notifications on this repo.

**Unfortunately I'm no longer using Atom and won't be maintaining this theme anymore.** I'll add a note to the `README` and will link to the more active forks.

Regardless of that: Thanks for using (and improving) an old little pet project of mine! 😃

**Comment by probablykasper** [comment]
Update: Package is maintained by me now, and I just published an update.

I made the teal color a little brighter:
![screen shot 2017-06-03 at 1 14 18 am](https://cloud.githubusercontent.com/assets/11315492/26747971/fd43e2b6-47f9-11e7-81d8-ecb80245c978.png)
